# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  push:
    branches: [ "main" ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: [ self-hosted ]
    
    env:
      AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Check out current commit (${{ github.sha }}, ${{ github.ref.name}})
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Set up Node V2
        uses: actions/setup-node@v2
        with:
          node-version: '18'
      
      - run: yarn install

      - name: Build & Deploy
        run: yarn workspaces since run "deploy" $(git rev-parse HEAD^)
